name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            driver: ''
          - os: windows-latest
            driver: hyperv
          - os: macos-latest
            driver: ''
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: ${{ matrix.driver }}
      - name: Install Tools for MacOs
        if: matrix.os == 'macos-latest'
        run: |
          brew install docker-machine docker
          brew cask install virtualbox
          sudo docker --version
          VBoxManage --version
          sysctl hw.physicalcpu hw.logicalcpu 
      - name: Install Tools for Windows
        if: matrix.os == 'windows-latest'
        run: |
            Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Tools-All
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Use Docker-Env Feature
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker images

