name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Install Tools for MacOs
        if: matrix.os == 'macos-10.15'
        run: |
          brew install docker-machine docker
          sudo docker --version
          VBoxManage --version
          sysctl hw.physicalcpu hw.logicalcpu 
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Use Docker-Env Feature
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker images

